//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int DepartmentID { get; set; }
        public string SpecificDepartment { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public string DomainUserName { get; set; }
        public string IpAddress { get; set; }
        public string MacAddress { get; set; }
        public string CN { get; set; }
        public string Password { get; set; }
        public bool ShowC { get; set; }
        public bool CanShare { get; set; }
        public bool UseDeskTop { get; set; }
        public bool Approved { get; set; }
        public int AuthTypeID { get; set; }
        public bool Usb { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual AuthType AuthType1 { get; set; }
    }
}
