//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_key
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long KeyID { get; set; }
    
        public virtual DomainUser DomainUser { get; set; }
        public virtual Ukey Ukey { get; set; }
    }
}
